-- Your SQL goes here
CREATE TABLE data_users (
    id INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL ,
    login TEXT NULL DEFAULT NULL,
    password TEXT NULL DEFAULT NULL,
    name TEXT NULL DEFAULT NULL,
    surname TEXT NULL DEFAULT NULL,
    patronymic TEXT NULL DEFAULT NULL,
    block INTEGER NOT NULL DEFAULT 0,
    last_active DATETIME NULL DEFAULT NULL
);